# http://www.appveyor.com/docs/appveyor-yml
environment:
  matrix:
    - nodejs_version: '8'

install:
  - yarn

test_script:
  - yarn test

cache:
  - node_modules -> package.json

version: "{build}"
build: off
deploy: off
matrix:
  fast_finish: true
