# http://www.appveyor.com/docs/appveyor-yml
environment:
  matrix:
    - nodejs_version: '8'

install:
  - choco install yarn
  - yarn --version
  - yarn

test_script:
  - yarn test

cache:
  - "%LOCALAPPDATA%\\Yarn"

version: "{build}"
build: off
deploy: off
matrix:
  fast_finish: true
